# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jimmy Lauzau
permalink: /blog/:year/:month/:day/:title
email: jimmy@jimmylauzau.com
description: > # this means to ignore newlines until "baseurl:"
  developer <a href="https://twitter.com/teamgaslight">@teamgaslight</a>, mountain biker, hiker, and dad
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jimmylauzau.com" # the base hostname & protocol for your site
twitter_username: jimmay5469
github_username:  jimmay5469

# Build settings
excerpt_separator: ""
markdown: kramdown

# Markdown Processors
kramdown:
  input: GFM
