name: Your New Jekyll Site
permalink: /blog/:year/:month/:day/:title

kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
